import { motion } from "framer-motion";
import { CalendarDays, CheckCircle2 } from "lucide-react";
import { useTrip } from "../../context/TripContext";
import { Panel } from "../../components/Panel";

export default function Itinerary() {
  const { plan } = useTrip();
  if (!plan) return null;

  return (
    <div className="space-y-5">
      <Panel title={`${plan.destination} · ${plan.days} days`} icon={CalendarDays}>
        <p className="text-sm text-mist">Generated by the Planner Agent based on your preferences, timing, and interests.</p>
      </Panel>

      <div className="relative pl-6 border-l-2 border-dashed border-border space-y-5">
        {plan.itinerary?.map((day, i) => (
          <motion.div
            key={day.day}
            initial={{ opacity: 0, x: -12 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.08 }}
            className="relative"
          >
            <span className="absolute -left-[31px] top-1 w-3.5 h-3.5 rounded-full bg-marigold border-4 border-ink" />
            <div className="card-glass rounded-2xl p-5">
              <div className="flex items-center justify-between mb-2">
                <p className="font-display text-lg text-paper">Day {day.day} — {day.title}</p>
              </div>
              <p className="text-sm text-mist mb-3">{day.summary}</p>
              <ul className="space-y-1.5">
                {day.activities?.map((a) => (
                  <li key={a} className="flex items-start gap-2 text-sm text-paper">
                    <CheckCircle2 size={15} className="text-teal mt-0.5 shrink-0" />
                    {a}
                  </li>
                ))}
              </ul>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
